"""create station table

Revision ID: 134e29cded17
Revises: ef774ffb0625
Create Date: 2025-06-16 14:13:27.611089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '134e29cded17'
down_revision = 'ef774ffb0625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('lang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('mood',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('music_genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('station',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('url_resolved', sa.String(length=500), nullable=False),
    sa.Column('homepage', sa.String(length=500), nullable=True),
    sa.Column('favicon', sa.String(length=500), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('countrycode', sa.String(length=10), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('codec', sa.String(length=20), nullable=True),
    sa.Column('bitrate', sa.Integer(), nullable=True),
    sa.Column('geo_lat', sa.Float(), nullable=True),
    sa.Column('geo_long', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('station', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_station_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_station_name'), ['name'], unique=False)

    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('station_decades',
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('decade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['decade_id'], ['decade.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['station.id'], ),
    sa.PrimaryKeyConstraint('station_id', 'decade_id')
    )
    op.create_table('station_langs',
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('lang_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lang_id'], ['lang.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['station.id'], ),
    sa.PrimaryKeyConstraint('station_id', 'lang_id')
    )
    op.create_table('station_moods',
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('mood_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mood_id'], ['mood.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['station.id'], ),
    sa.PrimaryKeyConstraint('station_id', 'mood_id')
    )
    op.create_table('station_musicgenres',
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('musicgenre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['musicgenre_id'], ['music_genre.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['station.id'], ),
    sa.PrimaryKeyConstraint('station_id', 'musicgenre_id')
    )
    op.create_table('station_topics',
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['station.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('station_id', 'topic_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('station_topics')
    op.drop_table('station_musicgenres')
    op.drop_table('station_moods')
    op.drop_table('station_langs')
    op.drop_table('station_decades')
    op.drop_table('topic')
    with op.batch_alter_table('station', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_station_name'))
        batch_op.drop_index(batch_op.f('ix_station_country'))

    op.drop_table('station')
    op.drop_table('music_genre')
    op.drop_table('mood')
    op.drop_table('lang')
    op.drop_table('decade')
    # ### end Alembic commands ###
