"""url resolved nullable

Revision ID: 24591112a682
Revises: d4f797a949ba
Create Date: 2025-06-16 14:35:16.913678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24591112a682'
down_revision = 'd4f797a949ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('station', schema=None) as batch_op:
        batch_op.alter_column('url_resolved',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('station', schema=None) as batch_op:
        batch_op.alter_column('url_resolved',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
